version: "3"

services:
  example_auth_postgres14:
    image: postgres:14
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: "${AUTH_POSTGRES_DBNAME}"
      POSTGRES_USER: "${AUTH_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${AUTH_POSTGRES_PASSWORD}"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    restart: on-failure
    ports:
      - 5442:5432
    volumes:
      - sticky_volume_auth_postgres:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env

  example_memberprofile_postgres14:
    image: postgres:14
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: "${MEMBER_PROFILE_POSTGRES_DBNAME}"
      POSTGRES_USER: "${MEMBER_PROFILE_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${MEMBER_PROFILE_POSTGRES_PASSWORD}"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    restart: on-failure
    ports:
      - 5452:5432
    volumes:
      - sticky_volume_memberprofile_postgres:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env

  example_auth_refresh_redis:
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - sticky_volume_auth_redis:/redis/data
      - ./config/redis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료 시 재시작 여부 설정
    restart: on-failure
    #    command: redis-server /usr/local/conf/redis.conf

  example_consul:
    image: consul:1.15.4
    ports:
      - "8501:8500"
    volumes:
      - ./config/consul/consul.conf:/config
      - ./config/consul/data:/data
    command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1
    restart: on-failure
    environment:
      CONSUL_LOCAL_CONFIG: '{"ui_config":{"enabled":true}, "connect": {"enabled": true}}'

volumes:
  sticky_volume_auth_postgres:
  sticky_volume_memberprofile_postgres:
  sticky_volume_auth_redis:
