server:
  port: 8080

spring:
  application:
    name: auth

  config:
    import:
      - app/jwt/jwt.yml
      - app/cors/cors.yml
      - app/jasypt/jasypt.yml
      - optional:file:.env[.properties]

  cloud:
    consul:
      host: localhost
      port: 8500
#      discovery:
#        instance-id: ${spring.application.name}:${random.value}
#        serviceName: myprefix-${spring.application.name}
#        healthCheckPath: /actuator/health
#        healthCheckInterval: 15s


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${AUTH_POSTGRES_URL}
    username: ${AUTH_POSTGRES_USERNAME}
    password: ${AUTH_POSTGRES_PASSWORD}
    hikari:
      connectionTimeout: 30_000
      idleTimeout: 600_000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 30_000
      leak-detection-threshold: 2000

  jpa:
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none # none or validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # (default)

logging:
  level:
    root: debug

