server:
  port: 8081

spring:
  application:
    name: member-profile

  config:
    import:
      - app/jasypt/jasypt.yml
      - optional:file:.env[.properties]

  cloud:
    consul:
      host: localhost
      port: 8500

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${MEMBER_PROFILE_POSTGRES_URL}
    username: ${MEMBER_PROFILE_POSTGRES_USERNAME}
    password: ${MEMBER_PROFILE_POSTGRES_PASSWORD}
    hikari:
      connectionTimeout: 30_000
      idleTimeout: 600_000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 30_000
      leak-detection-threshold: 2000

  jpa:
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none # none or validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # (default)

logging:
  level:
    root: debug
